<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ApplicationDefinition Include="ProcessAgentSampleApp.xaml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\source\Brows.ProcessAgent.Windows\Brows.ProcessAgent.Windows.csproj" />
  </ItemGroup>
</Project>
